### PR TITLE
fix(date): use available timezone if any

### LINKED ISSUE #81: bug: Tests fail locally if local timezone != UTC
### Describe the bug

running the tests locally it makes it fail when the timezone is not set to UTC. 
```
    --- FAIL: TestDateModify/AddTenMinutes (0.00s)
        functions_test.go:100: 
                Error Trace:    /sprout/pesticide/template_test_helpers.go:45
                Error:          Not equal: 
                                expected: "07 May 24 15:14 +0000"
                                actual  : "07 May 24 17:14 +0200"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -07 May 24 15:14 +0000
                                +07 May 24 17:14 +0200
                Test:           TestDateModify/AddTenMinutes
```

### To Reproduce

1. Set your timezone to a different one than UTC
2. Execute tests

### Expected behavior

_No response_

### Code Snippet

```Shell

```

### Version of software

latest main checkout

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ccoVeille**
## Description

It's important to use the date timezone if it has any.

## Changes

Do not switch back to Local timezone if not needed

## Checklist
- [X] I have read the **CONTRIBUTING.md** document.
- [X] My code follows the code style of this project.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [ ] I have updated the documentation accordingly.
- [ ] This change requires a change to the documentation on the website.

## Additional Information

Timezones are always fun

### CODE REVIEW

File: registry/time/functions_test.go [hunk 1]
```diff
@@ -8,17 +8,83 @@ import (
...
+		}
+
+		pesticide.RunTestCases(t, time.NewRegistry(), tc)
+	})
+
+	t.Run("New York timezone", func(t *testing.T) {
+		local, err := goTime.LoadLocation("America/New_York")
+		if err != nil {
+			t.Fatal(err)
+		}
```
Comment (42atomys) [inline registry/time/functions_test.go:35]:
```suggestion
		require.NoError(err)
```

File: registry/time/functions_test.go [hunk 2]
```diff
@@ -8,17 +8,83 @@ import (
...
+
+		pesticide.RunTestCases(t, time.NewRegistry(), tc)
+	})
+
+	t.Run("New York offset", func(t *testing.T) {
+		timeTest, err := goTime.Parse("02 Jan 06 15:04 -0700", "07 May 24 15:04 -0400")
+		if err != nil {
+			t.Fatal(err)
+		}
```
Comment (42atomys) [inline registry/time/functions_test.go:50]:
```suggestion
		require.NoError(err)
```

File: registry/time/functions_test.go [hunk 3]
```diff
@@ -8,17 +8,83 @@ import (
...
+
+		pesticide.RunTestCases(t, time.NewRegistry(), tc)
+	})
+
+	t.Run("New York timezone", func(t *testing.T) {
+		local, err := goTime.LoadLocation("America/New_York")
+		if err != nil {
+			t.Fatal(err)
+		}
```
Comment (42atomys) [inline registry/time/functions_test.go:64]:
```suggestion
		require.NoError(err)
```

File: registry/time/functions.go [hunk 4]
```diff
@@ -44,28 +49,32 @@ func (tr *TimeRegistry) Date(fmt string, date any) (string, error) {
...
+	loc, err := time.LoadLocation(zone)
+	if err != nil {
+		return t.In(time.UTC).Format(fmt), err
+	}
+
+	return t.In(loc).Format(fmt), nil
+}
+
+// computeTimeFromFormat returns a time.Time object from the given date.
+func computeTimeFromFormat(date any) time.Time {
```
Comment (42atomys) [inline registry/time/functions.go:62]: This function should be placer in `helpers.go` and have her tests in `helpers_test.go`

**Review by 42atomys — CHANGES_REQUESTED** [review]
Hi, my turn for `require` package ! 😄 

The catch of TZ in `Date` has something desired for future so nice addition

**Comment by ccoVeille** [comment]
There are more work to do. `toDate` is also affected by the "implicit" timezone conversion.

I started fixing locally, but now I'm busy IRL

**Comment by 42atomys** [comment]
No problem @ccoVeille IRL > all 
takes your time ! If you need help don't hesitate to ask me

**Comment by ccoVeille** [comment]
Added tests, fixed code, refactored a bit things that frustrated me

**Comment by 42atomys** [comment]
@ccoVeille fyi : some issues on tests on CI

**Comment by ccoVeille** [comment]
I'm still able to learn things about how timezones are handled after a few decades :sweat: 

And apparently, I'm not the only one
https://github.com/golang/go/issues/56528

https://pkg.go.dev/time#Parse
> When parsing a time with a zone offset like -0700, if the offset corresponds to a time zone used by the current location ([Local](https://pkg.go.dev/time#Local)), then Parse uses that location and zone in the returned time. Otherwise it records the time as being in a fabricated location with time fixed at the given zone offset.

> When parsing a time with a zone abbreviation like MST, if the zone abbreviation has a defined offset in the current location, then that offset is used. The zone abbreviation "UTC" is recognized as UTC regardless of location. If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset. This choice means that such a time can be parsed and reformatted with the same layout losslessly, but the exact instant used in the representation will differ by the actual zone offset. To avoid such problems, prefer time layouts that use a numeric zone offset, or use [ParseInLocation](https://pkg.go.dev/time#ParseInLocation).

Said otherwise, the format displaying a zone in addition of the format causes troubles, the result varies between the timezone, and only the one matching the `time.Local` one will have a zone. So to test this, we must temporarily force the time.Local, and handle all the use cases.

Another solution could be rewritten the test to avoid using a format including the zone, the time offset could be enough.

File: registry/time/helpers.go [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+}
+
+// ForceTimeLocal temporarily sets [time.Local] for test purpose.
+func ForceTimeLocal(t *testing.T, local *time.Location) {
+	t.Helper()
+
+	originalLocal := time.Local
+	time.Local = local
+	t.Cleanup(func() { time.Local = originalLocal })
+}
```
Comment (42atomys) [inline registry/time/helpers.go:34]: As a test helper, I prefer to declare it in a test file or in pesticide package to prevent import "testify" on the build tree

File: registry/time/helpers.go [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+		return time.Unix(date, 0)
+	case int:
+		return time.Unix(int64(date), 0)
+	case int32:
+		return time.Unix(int64(date), 0)
+	}
+
+	// otherwise, fallback to the current time
+	return time.Now().Local()
+}
```
Comment (42atomys) [inline registry/time/helpers.go:25]: This fonction are only for the time registry so this can be private

File: registry/time/functions_test.go [hunk 7]
```diff
@@ -2,39 +2,115 @@ package time_test
 
 import (
 	"testing"
-	goTime "time"
+	"time"
```
Comment (42atomys) [inline registry/time/functions_test.go:5]: If you decide to reverse the logic like that can you check we don't have another "std import with alias" on the codebase to be consistant please

File: registry/time/helpers_test.go [hunk 8]
```diff
@@ -0,0 +1,60 @@
+package time_test
```
Comment (42atomys) [inline registry/time/helpers_test.go:1]: On helpers_test you can be directly on the time package to test the private method ✅

**Review by 42atomys — CHANGES_REQUESTED** [review]

**Comment by 42atomys** [comment]
This kind of discovery are always interesting, discover something when dig deeper is a really good feeling

File: registry/time/helpers.go (hunk 5 above)
Comment (ccoVeille) [reply registry/time/helpers.go:34]: I don't get what you said, this function doesn't use testify :thinking:

File: registry/time/helpers_test.go [hunk 9]
```diff
@@ -0,0 +1,58 @@
+package time
+
+import (
+	"testing"
+	"time"
+
+	"github.com/stretchr/testify/assert"
+)
```
Comment (ccoVeille) [inline registry/time/helpers_test.go:8]: You asked me to make computeTimeFromFormat unexported, but then I have to switch the test into time package, and not the time_test one, so I'm adding testify

maybe it's what you were talking here https://github.com/go-sprout/sprout/pull/94/files#r1870643709

What would you suggest ?

Comment (42atomys) [reply registry/time/helpers_test.go:8]: `helpers_test.go` is always in the same package, while `functions_test.go` uses `package_test` to cover this use case, so everything is good here ✅

File: registry/time/helpers.go (hunk 5 above)
Comment (42atomys) [reply registry/time/helpers.go:34]: The function `ForceTimeLocal` are only used for test so moving it to the `pesticide` package to have clear separation between tests and lib usage. 

> to prevent import "testify"
A brain freeze, I don't wanna know why I have say that, because `t.Helper()` are from `testing` and not `testify`.. Sorry

File: .golangci.yaml [hunk 10]
```diff
@@ -19,6 +20,13 @@ linters:
     - usestdlibvars
 
 linters-settings:
+  importas:
+    alias:
+      # prevent conflicts with std packages
+      - pkg:  github.com/go-sprout/sprout/registry/time
+        alias: rtime
+      - pkg:  github.com/go-sprout/sprout/registry/strings
+        alias: rstrings
```
Comment (42atomys) [inline .golangci.yaml:29]: I see your issue #103, and you already add it here so I will link the issue, and to keep the same import logic across all registries, we can use the regex synthax to always have `r{package}` across the project 🥇 

```suggestion
      # prevent conflicts with std packages
      - pkg:  github.com/go-sprout/sprout/registry/(\w+)
        alias: r$1
```

File: registry/time/functions.go [hunk 11]
```diff
@@ -168,18 +157,16 @@ func (tr *TimeRegistry) UnixEpoch(date time.Time) string {
...
 // Returns:
+//   time.Time - the modified date after adding the duration
+//	 error - an error if the duration format is incorrect
 //
-//	  time.Time - the modified date after adding the duration
-//		 error - an error if the duration format is incorrect
-//
-// For an example of this function in a Go template, refer to [Sprout Documentation: dateModify].
-//
-// [Sprout Documentation: dateModify]: https://docs.atom.codes/sprout/registries/time#datemodify
```
Comment (42atomys) [inline registry/time/functions.go:182]: I think something went wrong with a merge conflict in this file.

**Review by 42atomys — CHANGES_REQUESTED** [review]

File: .golangci.yaml (hunk 10 above)
Comment (ccoVeille) [reply .golangci.yaml:29]: I assumed you wanted me to fix the import aliases in this PR.

I had no idea the importas could do that

File: registry/time/functions.go (hunk 11 above)
Comment (ccoVeille) [reply registry/time/functions.go:182]: Indeed. I cannot fix this now, but sure

Comment (ccoVeille) [reply registry/time/functions.go:182]: let me look at this

**Comment by ccoVeille** [comment]
@42atomys is there anything you wait from me?

**Comment by 42atomys** [comment]
@ccoVeille No I don't, I just wait the "request review" but I assume you have just forgot, I will review now and go forward if all are good 🏁

**Review by 42atomys — APPROVED** [review]
LGTM ✅
