### PR TITLE
fix: resolve issues with the v0.6.0-rc.1

### LINKED ISSUE #66: bug: multiple build occur growing wrapped function
### Describe the bug

I discover during the test of v0.6.0-rc1 something crazy, when we `handler.Build()` on a fresh handler all are good, but if we turn on safe mode and call `.Build()` multiple times, the wrapper will wrap again causing a wrapping loop (and also a memory grow).

### To Reproduce

1. Define a sprout handler
2. Enable safe mode (`sprout.WithSafeFunctions()`)
3. Execute multiple time `handler.Build()`
4. Show wrapped function growing N times (N are the count of `.Build` call)

### Expected behavior

When we re-call Build on an already builded function map, nothing must happend.

### Code Snippet

_No response_

### Version of software

v0.6.0-rc1

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 42atomys**
## Description
This pull requests grabs returns for the `v0.6.0-rc.1` (Release Candidate 1) and resolve issues related to it. 

## Changes
- Add `Raw` prefix to `Functions` and `Aliases` function to be more comprehensible and prevent confusion with `Funcs()` from sprig.
- Remove deprecated `NewFunctionhandler` labelled as deprecated in v0.2.0 to prepare the `v1.0.0`
- Ensure a built function map cannot be rebuild and cause memory growing
- Prevent to creating an alias on a no-existant function name

## Checklist
- [x] I have read the **CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated the documentation accordingly.
- [x] This change requires a change to the documentation on the website.

### CODE REVIEW

File: alias.go [hunk 1]
```diff
@@ -10,10 +10,15 @@ type FunctionAliasMap = map[string][]string
...
+		}
+
 		for _, alias := range aliases {
-			if fn, ok := h.Functions()[originalFunction]; ok {
-				h.Functions()[alias] = fn
+			if fn, ok := h.RawFunctions()[originalName]; ok {
+				h.RawFunctions()[alias] = fn
 			}
 		}
 	}
```
Comment (ccoVeille) [inline alias.go:24]: There is something strange to me you are checking if `h.RawFunctions()[originalName]` exists, but then you don't get the value

But then in the loop you look for `h.RawFunctions()[originalName]` to check if it exists (again) and then get its value

File: handler.go [hunk 2]
```diff
@@ -235,3 +235,22 @@ func safeFuncName(name string) string {
...
+	}
+
+	safeFuncs := make(FunctionMap)
+	for funcName, fn := range dh.cachedFuncsMap {
+		safeFuncs[safeFuncName(funcName)] = dh.safeWrapper(funcName, fn)
+	}
+
+	for funcName, fn := range safeFuncs {
+		dh.cachedFuncsMap[funcName] = fn
+	}
```
Comment (ccoVeille) [inline handler.go:255]:
```suggestion
	for safeFuncName, fn := range safeFuncs {
		dh.cachedFuncsMap[safeFuncName] = fn
	}
```

File: registry.go [hunk 3]
```diff
@@ -68,3 +68,29 @@ func AddAlias(aliasMap FunctionAliasMap, originalFunction string, aliases ...str
...
+}
+
+// WithRegistries returns a HandlerOption that adds the provided registries to the handler.
+// This option simplifies the process of adding multiple sets of functionalities into the
+// template engine at once.
+//
+// Example:
+//
+//	handler := New(WithRegistries(myRegistry1, myRegistry2, myRegistry3))
+func WithRegistries(registries ...Registry) HandlerOption[*DefaultHandler] {
```
Comment (ccoVeille) [inline registry.go:92]: I don't see a need for having WithRegistries and WithRegistry, the one using a variadic is enough

Comment (42atomys) [reply registry.go:92]: This is to follow the presence of `WithNotices` and `WithAlias`/`WithAliases`, let's discuss it to : 

1. Keep each 
2. Remove all "singular" option to keep only plural

File: handler.go [hunk 4]
```diff
@@ -104,26 +104,22 @@ func (dh *DefaultHandler) AddRegistries(registries ...Registry) error {
...
+// the same builded function map.
 //
 // NOTE: This will replace the `FuncsMap()`, `TxtFuncMap()` and `HtmlFuncMap()` from sprig
 func (dh *DefaultHandler) Build() FunctionMap {
+	if dh.built {
+		return dh.cachedFuncsMap
+	}
+
 	AssignAliases(dh) // Ensure all aliases are processed before returning the registry
 	AssignNotices(dh) // Ensure all notices are processed before returning the registry
```
[the remark this answers is not in the document]
Comment (42atomys) [reply handler.go:119]: `AssignAliases` and `AssignNotices` are bound to the `Handler` interface, not directly to the `DefaultHandler`. This allows other handlers to use the same feature without needing to re-implement it :)

[the remark this answers is not in the document]
Comment (42atomys) [reply handler.go:121]: I change the behavior of `buildSafeFuncs` to follow the same idea / convention and allow to use it externally with `AssignSafeFuncs(handler Handler)` instead of be dependent of DefaultHandler

File: registry.go (hunk 3 above)
Comment (42atomys) [reply registry.go:92]: @ccoVeille This is the only reaming point :)

Comment (ccoVeille) [reply registry.go:92]: I assumed it would be something like that.

I would say remove the ones without variadic.

Comment (ccoVeille) [reply registry.go:92]: Also, what about using the singular for the variadic?

It would be better I think. But it's up to you

File: handler.go [hunk 5]
```diff
@@ -56,6 +55,7 @@ type DefaultHandler struct {
 	notices    []FunctionNotice
 
 	wantSafeFuncs bool
+	built         bool
```
[the remark this answers is not in the document]
Comment (ccoVeille) [reply handler.go:58]: Did you change something here?

File: registry.go (hunk 3 above)
Comment (42atomys) [reply registry.go:92]: With your proposal, I prefer to keep only variadic too, singular seams to not reflect the usage of the function.

**Variadic Parameter**: The `registries ...Registry` parameter indicates that the function can accept multiple Registry instances, the name should reflect this capability. By using the plural form in the function name (e.g., WithRegistries), we make it clear to other developers that the function is intended to handle multiple registries, enhancing code readability and adherence to Go naming conventions.

I will reflect that ✅

**Review by ccoVeille — APPROVED** [review]
